### ISSUE TITLE
Reproducibility of simulation data 

### ISSUE THREAD

**Issue by demar01** [theislab/scib-reproducibility#17]
Hello, 
First of all, thank you for this fantastic package!

When I generate the simulated data sim1 from [here](https://github.com/theislab/scib-reproducibility/blob/main/notebooks/data_preprocessing/simulations/sim1.R) that Anndata does not contain a 'counts' layer in 'adata.layers[`counts`]', and therefore I cannot use it for the [integration part](https://github.com/theislab/scib-reproducibility/blob/main/notebooks/integration/scanvi.ipynb) 

Would it be possible to get the steps to generate the dataset used in the integration part, 
'/storage/groups/ml01/workspace/scIB/simulations_1_1/sim1_1_norm.h5ad'? Also that data should not be normalized, but the name is sim1_1_norm.h5ad? 

Many thanks!

**Comment by LuckyMD** [comment]
Hey! We ran scran normalization on the data to normalize it and put the data that was initially in `adata.X` in `adata.layers['counts']`. The function for that should just be `scib.pp.normalize()` from the scib package [here](www.github.com/theislab/scib). That should generate exactly the version of the simulation data you need. Maybe @lazappi can confirm this.

**Comment by LuckyMD** [comment]
Hey @demar01 
@lazappi just highlighted the simulation datasets were not on figshare, so I added them. You can find them [here](https://figshare.com/articles/dataset/Benchmarking_atlas-level_data_integration_in_single-cell_genomics_-_integration_task_datasets_Immune_and_pancreas_/12420968).

**Comment by demar01** [comment]
Thanks so much!!
