### ISSUE TITLE
construction of windows atac seq data

### ISSUE THREAD

**Issue by rLannes** [theislab/scib-reproducibility#18]
Hi, 

I would like to reproduce the analyses you have done. In particular, using windows and harmony and or liger. But it is unclear for me (I apologize if I miss the information) How do you manage to make the windows information. Did you map the fragment or the peaks on the genome bin?

Thank you for your help.

Furthermore, if by any chance you can share the pieces of code, that would be greatly appreciated.

**Comment by LuckyMD** [comment]
Hi @rLannes,

The preprocessing notebooks to get the windows can be found here.
https://github.com/theislab/scib-reproducibility/tree/main/notebooks/data_preprocessing/mouse_brain_atac/windows

If there's anything missing there, maybe @DaneseAnna, who did the ATAC preprocessing, can help you.

**Comment by rLannes** [comment]
Thank you for your answer, on the notebook the analysis starts loading the matrix cell * windows if I am not mistaken.
And I don't know how to get this matrix.

```
input_dir_10x = ''
adata = ad.read(input_dir_10x+'atac_v1_adult_brain_fresh_5k_fragments_AllCells.h5ad')
adata
```

@DaneseAnna I would really appreciate if you can help me on this one.

Romain

**Comment by DaneseAnna** [comment]
Hi Romain, 

Regarding the unprocessed h5ad windows objects ( not only "atac_v1_adult_brain_fresh_5k_fragments_AllCells.h5ad" but the other one as well) I am uploading them here as soon as I get to the office : https://www.dropbox.com/sh/13voksxb1lgz3p5/AADjuERFWkCKJRX8pjANWEJla?dl=0

About your initial question about how we obtain the window count matrices, yes we used the fragment files and mapped the reads directly. I need to check where the code @chaichoompu is for building the matrices, and I will add it to dropbox as well. 

Best, 
Anna

**Comment by LuckyMD** [comment]
Thanks a lot, @DaneseAnna! It might be useful to upload the code for this also to this github so that others can find it in future :).

**Comment by rLannes** [comment]
Great, thank you so much !
