### ISSUE TITLE
scANVI usability stats

### ISSUE THREAD

**Issue by adamgayoso** [theislab/scib-reproducibility#5]
Hi all,

The website looks great, I just came across the [usability](https://theislab.github.io/scib-reproducibility/usability.html) section.

It seems as though this hasn't been updated since scANVI's [publication](https://www.embopress.org/doi/full/10.15252/msb.20209620), which has a lot of updated content from the preprint. It also suggests scANVI has no tutorials, which we do have [here](https://docs.scvi-tools.org/en/stable/user_guide/notebooks/seed_labeling.html) and [here](https://docs.scvi-tools.org/en/stable/user_guide/notebooks/harmonization.html) and [here](https://docs.scvi-tools.org/en/stable/user_guide/notebooks/scarches_scvi_tools.html). We also have an R [tutorial](https://docs.scvi-tools.org/en/stable/user_guide/notebooks/scvi_in_R.html) with scVI.

Thanks! This will be a great resource for the community.

**Comment by LuckyMD** [comment]
Hi @adamgayoso,

Thanks for highlighting this! 

We have to think about whether we still have scope for updating the usability section further or whether we put a note that this is from November/December 2020. We're in the 2nd round of revisions now. Either way, we don't use usability for overall ranking and with the "not published" usability states I hope it will be quite clear that this is not continuously updated (or updatable).

**Comment by LuckyMD** [comment]
Yes, if we end up not updating, then we should definitely add the footnote. There's a good chance we forgot about that.
